language: node_js

os:
  - linux
  - osx

osx_image: xcode9.2

node_js:
  - "9"

cache:
  directories:
    - "node_modules"

script:
    - npm run build

after_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run dist; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run dist -- --mac --win; fi
